### PR TITLE
fix: `MapConfiguration.interaction_configuration` is not honoured

### LINKED ISSUE #3973: Changing the Map's Interactivity has no effect
### Discussed in https://github.com/flet-dev/flet/discussions/3958

<div type='discussions-op-text'>

<sup>Originally posted by **Michel7GitHub** September 10, 2024</sup>
### Question

I'm unable to disable Map Rotation. I test with Flet App on Mobile (iPad & iPhone). I used Windows 11, Flet versions 0.24.1 (both IOS and Windows).  I also tried `map.MapInteractiveFlag.NONE` without success. 
Here is the code I use:

```
import flet as ft
import flet.map as map

def main(page: ft.Page):

    page.add(
        map.Map(
            expand=True,
            configuration=map.MapConfiguration(
                initial_center=map.MapLatitudeLongitude(15, 10),
                initial_zoom=5,
                interaction_configuration=map.MapInteractionConfiguration(
                    flags=map.MapInteractiveFlag.ALL & ~map.MapInteractiveFlag.ROTATE
                )
            ),
            layers=[
                map.TileLayer(
                    url_template="https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                    on_image_error=lambda e: print("TileLayer Error"),
                ),
                map.MarkerLayer(
                    markers=[
                        map.Marker(
                            content=ft.Icon(ft.icons.LOCATION_ON),
                            coordinates=map.MapLatitudeLongitude(15, 10),
                        ),
                    ],
                )
            ],
        ),
    )

ft.app(target=main)
```

### Code sample

_No response_

### Error message

_No response_

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

### PR DESCRIPTION
**Pull request by ndonkoHenri**
## Description

Fixes #3973

## Summary by Sourcery

Fix the issue where `MapConfiguration.interaction_configuration` was not being honored by adding the `interactionOptions` to `MapOptions`. Enhance the map functionality by introducing support for pointer hover events, allowing the map to trigger a `pointer_hover` event with latitude, longitude, and pointer details.

Bug Fixes:
- Ensure `MapConfiguration.interaction_configuration` is correctly applied by adding the `interactionOptions` parameter to `MapOptions`.

Enhancements:
- Add support for handling pointer hover events on the map, triggering a `pointer_hover` event with relevant details.

### CODE REVIEW

**Review by FeodorFitsner — APPROVED** [review]

**Review by FeodorFitsner — APPROVED** [review]

**Comment by Michel7GitHub** [comment]
Hi,
I just installed Flet v0.25.0 Release but the problem is still present : MapConfiguration.interaction_configuration is not honoured. 
I tried these flags  `flags=map.MapInteractiveFlag.ALL & ~map.MapInteractiveFlag.ROTATE`
I tested on Windows 11.
I also tried to test on IOS (iPad & iPhone), but Map doesn't display !!! I have to regress to Flet v0.24.1

**Comment by ndonkoHenri** [comment]
It works on my mac:
```python
import random
import flet as ft
import flet.map as map


def main(page: ft.Page):

    page.add(
        map.Map(
            expand=True,
            initial_center=map.MapLatitudeLongitude(15, 10),
            initial_zoom=4.2,
            interaction_configuration=map.MapInteractionConfiguration(
                flags=map.MapInteractiveFlag.NONE
            ),
            on_init=lambda e: print(f"Initialized Map"),
            layers=[
                map.TileLayer(
                    url_template="https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                    on_image_error=lambda e: print("TileLayer Error"),
                ),
            ],
        ),
    )


ft.app(main)
``` 

Give the above a try.

**Comment by Michel7GitHub** [comment]
Hi ndonkoHenri,
I tried your code on Windows and all flags get OFF (this is OK) BUT the one I want OFF still ON ... Rotate Flag !
Did you try to Rotate on Mac?
I tried your code on iPad (v0.24.1 app) and Windows 11 as server with v0.25.0... Map doesn't display.
Should I update IOS App version ? I don't find new version on AppStore.
I don't know if it's important, but I receive this message (show on my Windows 11 server) when I tried on IOS (iPad) :
`C:\Python312\Lib\site-packages\websockets\legacy\server.py:1177: DeprecationWarning: remove second argument of ws_handler warnings.warn("remove second argument of ws_handler", DeprecationWarning)`

**Comment by ndonkoHenri** [comment]
Yes it works too: 
```python
interaction_configuration=map.MapInteractionConfiguration(flags=map.MapInteractiveFlag.ALL & ~map.MapInteractiveFlag.ROTATE)
``` 
Will give it a try on my Windows when possible.

Concerning the Flet app, we are working on updating it to support changes made in 0.25.0

**Pull request merged**
