### PR TITLE
Android Predictive Back Support Google TV

### PR DESCRIPTION
**Pull request by syleishere**
## Description
https://docs.flutter.dev/release/breaking-changes/android-predictive-back

Without Predictive back support, the Google TV Streamer Flet app will just crash hitting back button on remote, a much better way to do this is confirm with user they want to exit app by simply telling them to hit the back button again with a simple snackbar message, and kill Flet app at that point.

## Test Code

No test code needed, direct integration into code base.

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] This change requires a documentation update

## Checklist

- [ x ] I signed the CLA.
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings
- [ x ] New and existing tests pass locally with my changes
- [ ] I have made corresponding changes to the [documentation](https://github.com/flet-dev/website) (if applicable)

## Additional details

Solves another Google TV issue.

## Summary by Sourcery

Implement predictive back navigation support for Google TV in the Flet app, allowing users to confirm exit with a snackbar message. Integrate audio service for enhanced media control and update AndroidManifest.xml to support new features.

New Features:
- Add predictive back navigation support for Google TV in the Flet app, allowing users to confirm exit with a snackbar message before closing the app.

Enhancements:
- Integrate audio service to manage audio playback and notifications, improving media control and user experience.

Build:
- Update AndroidManifest.xml to include necessary permissions and services for audio playback and Bluetooth connectivity.

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
This PR contains some stuffs from your audio-PR: https://github.com/flet-dev/flet/pull/4565/files

**Comment by syleishere** [comment]
Ahh ok thanks for letting me know, I'll fix it after weekend. I must have accidently cloned my own branch repo instead of flet's

**Comment by syleishere** [comment]
Actually I'm not happy with this PR, I am going to completely kill it and start new. No one is going to be happy unless that snackbar message is configurable, at first I was thinking let's do it with page.popscope, then I thought people are going to be like wtf is page.popscope. So a page.back_exit_message I think is best name I could come up with. Thought just page.exit_message at first, then I thought that's vague again, just closing your app does not trigger this, back button on google TV does, or back button on an android device.

**Comment by syleishere** [comment]
Ok next problem is people may not want this functionality added at all, so I am proposing 2 flet page variables:
page.back_exit_enabled = False
page.back_exit_message = "Press again to exit"

Disabled by default, but can be enabled say specifically on google TV.

Ok I think this is right approach, then affects nothing, but adds functionality if someone wants it.

**Comment by SIRGPrice** [comment]
Android back button event capture and use in routing and exit solved and proved with other people here: https://github.com/flet-dev/flet/discussions/4495#discussioncomment-11634586

**Comment by syleishere** [comment]
> Android back button event capture and use in routing and exit solved and proved with other people here: [#4495 (reply in thread)](https://github.com/flet-dev/flet/discussions/4495#discussioncomment-11634586)

Have you tested it on Google TV? Hitting back button there will exit your app to main TV screen no matter how you try to trap it with flet generally, why I wrapped dart scaffold with pop scope.

**Comment by SIRGPrice** [comment]
> > Android back button event capture and use in routing and exit solved and proved with other people here: [#4495 (reply in thread)](https://github.com/flet-dev/flet/discussions/4495#discussioncomment-11634586)
> 
> Have you tested it on Google TV? Hitting back button there will exit your app to main TV screen no matter how you try to trap it with flet generally, why I wrapped dart scaffold with pop scope. If you print message for keybinding when hitting back button on remote it says "GO BACK", and you cannot even trap that on flet without it returning to main screen. Popscope was only effective way to trap in on Google TV streamer when I tried.
> 
> This was really PR for Google TV, I don't see why anyone would want to trap it otherwise, why I reopened a PR for it disabling it by default unless someone wants to make sure their app works there as well.

I didnt try it sorry, im talking only for mobiles. You need some help with that?

**Comment by syleishere** [comment]
> > > Android back button event capture and use in routing and exit solved and proved with other people here: [#4495 (reply in thread)](https://github.com/flet-dev/flet/discussions/4495#discussioncomment-11634586)
> > 
> > 
> > Have you tested it on Google TV? Hitting back button there will exit your app to main TV screen no matter how you try to trap it with flet generally, why I wrapped dart scaffold with pop scope. If you print message for keybinding when hitting back button on remote it says "GO BACK", and you cannot even trap that on flet without it returning to main screen. Popscope was only effective way to trap in on Google TV streamer when I tried.
> > This was really PR for Google TV, I don't see why anyone would want to trap it otherwise, why I reopened a PR for it disabling it by default unless someone wants to make sure their app works there as well.
> 
> I didnt try it sorry, im talking only for mobiles. You need some help with that?

Nope, I don't really see a use for it on mobiles, everyone always backgrounding apps there which works fine.

**Comment by SIRGPrice** [comment]
> > > > Android back button event capture and use in routing and exit solved and proved with other people here: [#4495 (reply in thread)](https://github.com/flet-dev/flet/discussions/4495#discussioncomment-11634586)
> > > 
> > > 
> > > Have you tested it on Google TV? Hitting back button there will exit your app to main TV screen no matter how you try to trap it with flet generally, why I wrapped dart scaffold with pop scope. If you print message for keybinding when hitting back button on remote it says "GO BACK", and you cannot even trap that on flet without it returning to main screen. Popscope was only effective way to trap in on Google TV streamer when I tried.
> > > This was really PR for Google TV, I don't see why anyone would want to trap it otherwise, why I reopened a PR for it disabling it by default unless someone wants to make sure their app works there as well.
> > 
> > 
> > I didnt try it sorry, im talking only for mobiles. You need some help with that?
> 
> Nope, I don't really see a use for it on mobiles, everyone always backgrounding apps there which works fine. The only exception I have seen not needing it on Google tv is if your running a background service like flutters audio service, then app will resume fine, I have a patch in for flet video for that so can play song lists in background on mobile, iOS, Google tv with full Bluetooth support etc.

The main reason is that you need a base group of routing methods that allow to go and back inside the app that replicates its behaviour whatever is the source  (in this case de android integrated back button) of the go or back event to allow user to get progresive advance forwards and backwards in the diferent pages.

**Pull request closed without merging**
