### PR TITLE
added `star-history`

### PR DESCRIPTION
**Pull request by hemangjoshi37a**
added `star-history`

### CODE REVIEW

**Comment by hemangjoshi37a** [comment]
Also please take a look at my issue : #1067

**Comment by FeodorFitsner** [comment]
I, honestly, a little hesitate to put that chart into the readme :) Such charts are good when starts are growing. But what would we do in case the growth slows down - remove the chart?

**Comment by hemangjoshi37a** [comment]
> I, honestly, a little hesitate to put that chart into the readme :) Such charts are good when starts are growing. But what would we do in case the growth slows down - remove the chart?

It's not about showing the growth. its about being real and authentic about how things were and how things are now. It might be possible that if the growth slows down someone might take interest to revive the project through PRs.

**Comment by hemangjoshi37a** [comment]
> I, honestly, a little hesitate to put that chart into the readme :) Such charts are good when starts are growing. But what would we do in case the growth slows down - remove the chart?

Regardless it's just cool. 🆒 😎

**Pull request closed without merging**
