### PR TITLE
Merged this some days ago but they still show.

### PR DESCRIPTION
**Pull request by techemmy**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
What is this PR about?

**Comment by techemmy** [comment]
It is the pull request I made the last time but it still shows on my repo.

**Comment by FeodorFitsner** [comment]
OK, but it changes 0 files: https://github.com/flet-dev/flet/pull/307/files

**Comment by techemmy** [comment]
> OK, but it changes 0 files: https://github.com/flet-dev/flet/pull/307/files

Yes

**Comment by techemmy** [comment]
And it mentioned the last merge as a change.

**Pull request closed without merging**
