### PR TITLE
Unify all `open_...()` and `close_...()` methods into `open()` and `close()`

### LINKED ISSUE #3367: Feature request: Unify all open_...() method into open()
**Please Describe The Problem To Be Solved**

Feodor said in review of my pull (#3172) that it'll be great if will there is open() method. I'm requesting to add this in my future pull and requesting realisation. f. e.

```py
page.open('drawer')
# or
drawer = ...
page.open('drawer', drawer)
```

Also it'll great that will there is close() method

```py
page.close('drawer')
```

### PR DESCRIPTION
**Pull request by bleudev**
TODO:
- [ ] `open()`
  - [x] Signature
  - [x] Realisation
  - [x] Type check
  - [x] Deprecations
  - [ ] Documentation
- [ ] `close()`
  - [x] Signature
  - [x] Realisation
  - [x] Type check
  - [x] Deprecations
  - [ ] Documentation
- [ ] Isort and black formating

closes #3367

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
Please can you pause on this work? I am coming with a PR for this.

**Comment by bleudev** [comment]
> Please can you pause on this work? I am coming with a PR for this.

i wanted to create this myself)

**Comment by ndonkoHenri** [comment]
Hey @bleudev, here is the PR: #3406

**Comment by bleudev** [comment]
> Hey @bleudev, here is the PR: #3406 Please give it a check so you don't do some already done work. 😉
> 
> Thanks for your contributions.

I looked at your PR and your open() isn't that what i'd like to see. I wanted to use open() with auto-define property when property isn't in page.

f.e.
```
# your open()
page.drawer = drawer
page.open(page.drawer)

# my
page.open('drawer', drawer)
```

**Comment by bleudev** [comment]
> > Hey @bleudev, here is the PR: #3406 Please give it a check so you don't do some already done work. 😉
> > Thanks for your contributions.
> 
> I looked at your PR and your open() isn't that what i'd like to see. I wanted to use open() with auto-define property when property isn't in page.
> 
> f.e.
> 
> ```
> # your open()
> page.drawer = drawer
> page.open(page.drawer)
> 
> # my
> page.open('drawer', drawer)
> ```

Also i remember your words, that all PRs must be separate) My - about only open() and close(), your - about many things

**Comment by ndonkoHenri** [comment]
> I looked at your PR and your open() isn't that what i'd like to see. 

I had a little discussion with @FeodorFitsner about how the `open()` and `close()` should work and we agreed on that it should have the bare minimum - just modify the `open` property of the provided `Control` to `True` and `False` respectively. With this we will also be able to open Date- and TimePickers, and not only the control in page/offstage controls like Drawers and Rails.

> Also i remember your words, that all PRs must be separate) My - about only open() and close(), your - about many things

Yep, took advantage of that to do some additional cleanup :)

**Comment by bleudev** [comment]
> I had a little discussion with @FeodorFitsner about how the `open()` and `close()` should work and we agreed on that it should have the bare minimum - just modify the `open` property of the provided `Control` to `True` and `False` respectively. This way, one will also be able to open Date- and TimePickers for example, and not only the control in page/offstage controls like Drawers and Rails.

Ok, can you make possibility to use all 2 ways? For example,
```py
page.open(page.drawer)
# and
drawer = ...
page.open('drawer', drawer)
```

If you'll make this, nothing will be changed)

**Comment by ndonkoHenri** [comment]
The user should instead do it as follows 😉

```python
page.drawer = drawer
page.open(drawer)
```

**Comment by bleudev** [comment]
> The user should instead do it as follows 😉
> 
> ```python
> page.drawer = drawer
> page.open(page.drawer) # or page.open(drawer)
> ```
> 
> The goal is to keep those methods as simple and straightforward as possible. :)

Ok. Thanks. Now i'll close my PR because of uselessly

**Pull request closed without merging**
