### PR TITLE
Table calendar and Date Picker

### PR DESCRIPTION
**Pull request by berecik**
Calendar view base on: https://pub.dev/packages/table_calendar

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
so, you decided to combine DatePicker and Calendar in one PR?

**Comment by berecik** [comment]
> so, you decided to combine DatePicker and Calendar in one PR?

both need the same change in package/lib/src/models/control.dart so otherwise will be conflict in merge

**Comment by hemangjoshi37a** [comment]
Please reviewers merge this PR . This is very userful.

**Comment by FeodorFitsner** [comment]
It's not ready for the merge: there are conflicts and CI is failing.

**Comment by pashkatrick** [comment]
any updates?

**Comment by FeodorFitsner** [comment]
Close in favor of #1998
Will open a new PR if decide to implement https://pub.dev/packages/table_calendar

**Comment by iron3oxide** [comment]
> Close in favor of #1998 Will open a new PR if decide to implement https://pub.dev/packages/table_calendar

Once 1.0 is released, it would be cool if a Calendar control such as https://pub.dev/packages/table_calendar or https://pub.dev/packages/kalender could be added

**Pull request closed without merging**
