### PR TITLE
Standalone Flet web apps with Pyodide

### PR DESCRIPTION
**Pull request by FeodorFitsner**
* Migrated to Flutter 3.7 - minimal version of macOS supported is now 10.14.
* `Tabs.scrollable`
* `loading_animation.png` renamed to `loading_animation.svg` - either provide `.svg` or change `index.html` to load `.png`.

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
> or change index.html to load .png.
what do you mean here please?

**Comment by FeodorFitsner** [comment]
The image was renamed from `.png` to `.svg`, so if you have a custom `loading_animation.png` in `assets` and update to the latest version your customization will break.

**Comment by ndonkoHenri** [comment]
Yeah I got that. I mean what do you mean by 'change index.html to load .png'?

**Comment by FeodorFitsner** [comment]
You can grab a copy of index.html and put it into assets directory.

**Comment by FeodorFitsner** [comment]
I just wanted more "crisp" animation - SVG is for that and the image takes around 1K :)

**Pull request merged**
