### PR TITLE
Fix for issue in build_update_commands() when checking for commands attrs id.

### PR DESCRIPTION
**Pull request by Ewen-Zippedscript**
Fixed issue with `if cmd.name == "add" and any(c for c in cmd.commands if c.attrs["id"] == ctrl.__uid):` 
because some commands may not have the id value so now it's `if cmd.name == "add" and any( c for c in cmd.commands if c.attrs.get("id") == ctrl.__uid ):

### CODE REVIEW

**Comment by Ewen-Zippedscript** [comment]
As far as I can tell the issue happens when replacing an existing control with an identical copy and since the copy doesn't have a uid yet it throws that error.

**Comment by FeodorFitsner** [comment]
Would you share a repro code for that?

**Comment by Ewen-Zippedscript** [comment]
Quick rough example: 
```
Command(indent=0, name=None, values=['responsiverow'], attrs={}, commands=[])
Command(indent=2, name=None, values=['textfield'], attrs={'col': '{"sm":12,"md":10,"xl":4}', 'label': 'Name', 'value': '', 'id': '_115'}, commands=[])
Command(indent=2, name=None, values=['elevatedbutton'], attrs={'col': '{"sm":12,"md":2,"xl":2}', 'icon': 'get_app_outlined', 'text': 'Fill', 'id': '_116'}, commands=[])
```
are the commands for this code
```
if not self._controls:
    self.name_field = ft.TextField(label="Name",
                                value=self._name,   
                                col=field_col)
    self.name_fill = ft.ElevatedButton(text="Fill",
                                    icon=ft.icons.GET_APP_OUTLINED,
                                    on_click=self.fill_name,
                                    col=fill_col)
self._controls = [ft.ResponsiveRow([self.name_field, self.name_fill])]
```


When removing the check for controls:
```
Command(indent=0, name=None, values=['responsiverow'], attrs={}, commands=[])
Command(indent=2, name=None, values=['textfield'], attrs={'col': '{"sm":12,"md":10,"xl":4}', 'label': 'Name', 'value': ''}, commands=[])
Command(indent=2, name=None, values=['elevatedbutton'], attrs={'col': '{"sm":12,"md":2,"xl":2}', 'icon': 'get_app_outlined', 'text': 'Fill'}, commands=[])
```

code: 
```
self.name_field = ft.TextField(label="Name",
                            value=self._name,
                            col=field_col)
self.name_fill = ft.ElevatedButton(text="Fill",
                                icon=ft.icons.GET_APP_OUTLINED,
                                on_click=self.fill_name,
                                col=fill_col)
self._controls = [ft.ResponsiveRow([self.name_field, self.name_fill])]
```

**Comment by Ewen-Zippedscript** [comment]
I've written a script that throws the same error. 
```
import flet as ft



class Field:
    def __init__(self,page:ft.Page):
        self.page = page
        self._controls = []
        
        self.control = None
        self._update()

    def setup(self):
        name = ft.TextField(label="Name",)
        f = ft.TextField(label="Second",)

        self._controls = [name,f]

    def _update(self,):
        if not self.control:
            self.setup()
            self.control = ft.Container(ft.Column(self._controls))
        try:
            self.control.update()
        except:
            pass
        # self.page.update()


class View:
    def __init__(self,page:ft.Page):
        self.page = page
        self._controls = []
        self.fields = []
        self.setup()
        self.view = ft.View("/",self._controls)

        self.add_field(None)
        self.add_field(None)
    def setup(self):
        self.add = ft.ElevatedButton("Add Row",on_click=self.add_field,col=4)
        self.single_field = ft.TextField(label="single_field",col=8)
        self._controls = [ft.ResponsiveRow([self.add, self.single_field]),]
        for field in self.fields:
            self._controls.append(
                ft.Column([
                    ft.Divider(color=ft.colors.BLACK26),
                    ft.ElevatedButton(
                        text=f"Remove field {self.fields.index(field)}",
                        icon=ft.icons.REMOVE_CIRCLE,
                        on_click=lambda _: self.remove_field(field))
                ]))
            self._controls.append(field.control)
    def add_field(self,e):
        self.fields.append(Field(self.page))
        self._update()
    def remove_field(self, degree):
            self.fields.remove(degree)
            self._update()
    def _update(self):
        self.setup()
        if self.view:
            self.view.controls = self._controls
        try:
            self.view.update()
        except:
            pass
        for i in self._controls:
            try:
                i.update()
            except:
                pass
        self.view.controls = self._controls
        self.page.update()

class FlutterApp:
    def __init__(self):
        self.page = None
        

    def main(self,page:ft.Page):
        self.page = page
        self.main_v = View(page)
        self.page.views.append(self.main_v.view)
        self.page.update()
        
    

app = FlutterApp()
ft.app(target=app.main,view=ft.FLET_APP)
```

**Pull request merged**
