### PR TITLE
Flet Map

### PR DESCRIPTION
**Pull request by harunkurtme**
### I created Flet Map.

#

### CODE REVIEW

**Comment by harunkurtme** [comment]
> ### I created Flet Map.
> #### You input longtitude and latitude, show column and row showing images like flutter_map, some issue it have, not directly loading images and you refresh screen.
>

**Comment by FeodorFitsner** [comment]
I suggest renaming control to `OpenStreetMap`. FletMap is too generic.
Later we could have other implementations such as `GoogleMap`.

**Comment by ndonkoHenri** [comment]
An API key is required as per google maps [docs](https://pub.dev/packages/google_maps_flutter), and it is only for the mobile platforms. 

What of [flutter_map](https://pub.dev/packages/flutter_map) ? 🤔

**Comment by mikaelho** [comment]
If I understand correctly, this version breaks if `screenview` parameter is not provided. With the addition of `Canvas` component to `flet`, this component could be wrapped in it to use the `on_resize` handler to adjust the tile dimensions automatically to the space available for the map component, removing the need for `screenview`.

**Comment by FeodorFitsner** [comment]
I think https://github.com/flet-dev/flet-contrib would be a better home for this control.

@harunkurtme are you still available to move it to contribs?

**Comment by harunkurtme** [comment]
I saw new,

Okey master, I will add this contribs. 
@FeodorFitsner

**Comment by bibibo-77** [comment]
Hello, sorry for my comment. I would like to know, is it something new about Flet map support ? It's a very good project, but the map support is a bit lacking for me, :-(

**Comment by VioletBenin** [comment]
I also think it would be a good function deserves to be developed

**Comment by harunkurtdev** [comment]
Hello all,

I didn't interested in FletMap, you can run at inside this package. 
I left a link below, you can check whether it is approved or not via this pull request.

@bibibo-77 @VioletBenin @Insighttful @mikaelho 

(Flet-Contrib)[https://github.com/flet-dev/flet-contrib/pull/17#issue-2195578273]

**Pull request closed without merging**
