### PR TITLE
[#1564] fix `ValueError` on web page resize

### PR DESCRIPTION
**Pull request by ndonkoHenri**
#1564

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
Alright. I added one commit for `on_scroll_interval`

**Comment by ndonkoHenri** [comment]
Should I clean the PR (removing the null stuffs) ?

**Comment by FeodorFitsner** [comment]
I guess the fix should be somewhere in Dart, no?

**Comment by ndonkoHenri** [comment]
Check this: https://github.com/flet-dev/flet/pull/1565/commits/36efde6bc27b36b17d3afd24a536755c9e0f5c05

Add it while solving the float issue and I will close this PR and the related issues.

**Pull request closed without merging**
