### PR TITLE
fix/feat: make `SearchBar`'s view height adjustable; add new properties

### LINKED ISSUE #3985: Make it possible to change SearchBar's view height
### Discussed in https://github.com/flet-dev/flet/discussions/3983

<div type='discussions-op-text'>

<sup>Originally posted by **Dave-d-1st** September 13, 2024</sup>
### Question

Is there a way to change the view height of a search bar as to fit its contents in a specific way because it looks kind of weird when there's only few items in the view and the entire view height is being displayed

### Code sample

_No response_

### Error message

_No response_

### ------------------------------------------------------

- [X] I have searched for answers to my question both in the issues and in previous discussions.</div>

### PR DESCRIPTION
**Pull request by ndonkoHenri**
## Description
Fixes #3985 #4081

## Test Code

```python
import flet as ft


def main(page: ft.Page):
    page.window.always_on_top = True
    page.theme_mode = ft.ThemeMode.LIGHT
    page.add(
        ft.SearchBar(
            controls=[ft.ListTile(title=ft.Text("Hello"))],
            view_header_height=30,
            on_tap=lambda e: e.control.open_view(),
            width=350,
            view_size_constraints=ft.BoxConstraints(max_height=170, max_width=350),
            bar_hint_text="Search",
            bar_hint_text_style={
                ft.ControlState.HOVERED: ft.TextStyle(color=ft.colors.YELLOW, size=20)
            },
            bar_padding=ft.padding.symmetric(10, 10),
            bar_text_style=ft.TextStyle(color=ft.colors.RED, size=20),
            bar_border_side=ft.BorderSide(color=ft.colors.BLUE, width=2),
            bar_shape=ft.RoundedRectangleBorder(radius=0),
            bar_elevation=00.0,
            view_elevation=5.0,
            bar_shadow_color=ft.colors.BLUE,
        )
    )


ft.app(target=main, view=ft.AppView.WEB_BROWSER)

```

## Summary by Sourcery

Fix the `SearchBar` component to make its view height adjustable and enhance it by adding properties for view size constraints and header height, allowing for more flexible layout configurations.

Bug Fixes:
- Fix the issue with the `SearchBar` component by making its view height adjustable.

Enhancements:
- Add support for `view_size_constraints` and `view_header_height` properties in the `SearchBar` component to allow more flexible layout configurations.

## Summary by Sourcery

Make the `SearchBar` component's view height adjustable and enhance its flexibility by adding new properties for layout and style customization. Introduce utility functions for parsing widget state properties to support dynamic configurations.

Bug Fixes:
- Fix the issue with the `SearchBar` component by making its view height adjustable.

Enhancements:
- Add support for `view_size_constraints` and `view_header_height` properties in the `SearchBar` component to allow more flexible layout configurations.
- Introduce new properties for `SearchBar` such as `bar_shadow_color`, `bar_surface_tint_color`, `bar_elevation`, `bar_border_side`, `bar_shape`, `bar_text_style`, `bar_hint_text_style`, and `bar_padding` to enhance customization options.
- Implement new utility functions for parsing widget state properties, including `parseWidgetStateDouble`, `parseWidgetStateInt`, `parseWidgetStateBool`, `parseWidgetStateEdgeInsets`, `parseWidgetStateOutlinedBorder`, and `parseWidgetStateTextStyle` to support dynamic property handling.

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
@sourcery-ai review

**Review by FeodorFitsner — APPROVED** [review]

**Comment by ClearSafety** [comment]
Hi,
Thank you for that.
I've just upgrade the Flet but even so the new properties aren't available. Will they be available in  a new version realise?

**Comment by ndonkoHenri** [comment]
They are available in the latest prerelease: `pip install flet --pre -U`

**Comment by ClearSafety** [comment]
@ndonkoHenri 
Hi,
I'm trying to set 'bar_border_side', but it has no effect in the SearchBar.
I tried your own example, but nor border is displayed


import flet as ft


def main(page: ft.Page):
    page.window.always_on_top = True
    page.theme_mode = ft.ThemeMode.LIGHT
    page.add(
        ft.SearchBar(
            controls=[ft.ListTile(title=ft.Text("Hello"))],
            view_header_height=30,
            on_tap=lambda e: e.control.open_view(),
            width=350,
            view_size_constraints=ft.BoxConstraints(max_height=170, max_width=350),
            bar_hint_text="Search",
            bar_hint_text_style={
                ft.ControlState.HOVERED: ft.TextStyle(color=ft.colors.YELLOW, size=20)
            },
            bar_padding=ft.padding.symmetric(10, 10),
            bar_text_style=ft.TextStyle(color=ft.colors.RED, size=20),
            bar_border_side=ft.BorderSide(color=ft.colors.BLUE, width=2),
            bar_shape=ft.RoundedRectangleBorder(radius=0),
            bar_elevation=00.0,
            view_elevation=5.0,
            bar_shadow_color=ft.colors.BLUE,
        )
    )


ft.app(target=main, view=ft.AppView.WEB_BROWSER)****

**Comment by ndonkoHenri** [comment]
@ClearSafety i opened an issue: https://github.com/flet-dev/flet/issues/4767

**Pull request merged**
