### PR TITLE
Fix: View with content crashes in some routing scenarios

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
What was the issue please?
You can push a prerelease so I can give it a try.

**Comment by FeodorFitsner** [comment]
Racing condition. It occurs with Flutter animations/transitions, like in your case a routing view has been already removed from a page, but routing animation is still happening.

**Comment by FeodorFitsner** [comment]
You can try the fix with pre-release. It's ready.

**Comment by ndonkoHenri** [comment]
Hey! I just tried with the latest pre, and same issue. `Requirements.txt: flet==0.5.0.dev1181`
https://startup-name-generator.pages.dev/

**Comment by FeodorFitsner** [comment]
It's still loading 0.4.0, not the latest pre. You should publish it with `--pre`:

```
flet publish your-script.py --pre
```

image

**Comment by ndonkoHenri** [comment]
Ah, i  forgot that parameter.
Feed-back tomorrow please 😴

**Comment by ndonkoHenri** [comment]
Hey. It's still not working. Can you check if the flet pre was successfully loaded?

**Comment by FeodorFitsner** [comment]
If you look at `index.html` sources you'll see that loading of pre-release packages from PyPI is not enabled (`flet publish your-script.py --pre` sets it to `true`):

image

and it's still loading 0.4.0:

image

**Comment by ndonkoHenri** [comment]
I ran it with the `--pre` this Time.
No Problem, I will do it once more, and let you know.

**Pull request merged**
