### PR TITLE
`flet build` command to package Flet app for any platform

### PR DESCRIPTION
**Pull request by FeodorFitsner**
## Prerequisites

* Flutter SDK
* XCode

## How it works

Ephemeral - don't need to check-in, rebuild to get the latest updates.

* Create a new Flutter project in a temp directory from https://github.com/flet-dev/flet-build-template template. You can provide a customized template with `--template`, `--template_dir` and `--template_ref` parameters (see below). Flutter app contains a packaged Python app in the assets and uses `flet` and `serious_python` packages to run Python app and render a UI.
* Copy icon and splash images (see below) from `assets` directory.
* Generate icons using [`flutter_launcher_icons`](https://pub.dev/packages/flutter_launcher_icons) package.
* Generate splash screens using [`flutter_native_splash`](https://pub.dev/packages/flutter_native_splash) package.
* Package Python app using `package` command of [`serious_python`](https://pub.dev/packages/serious_python) package.
* Run `flutter build` command.
* Copy build results to `build/{platform}` directory.

## Target platform matrix

The following matrix shows which platform you should build on to target specific platforms:

| Build on / Target  |   ipa   |   apk/aab   |   macos    |   linux    |   windows    |    web    |
| :----------------: | :-----: | :---------: | :--------: | :--------: | :----------: | :--------: |
| macOS              |   ✅    |       ✅     |      ✅    |           |              |     ✅     |
| Windows            |         |       ✅     |            |  ✅ (WSL)  |      ✅      |     ✅     |
| Linux              |         |       ✅     |            |     ✅     |              |     ✅     |

## `flet build web`

You can test a published web app using Python's built-in [http.server module](https://docs.python.org/3/library/http.server.html):

```
python -m http.server --directory build/web
```

Open `http://localhost:8000` in your browser to check the published app.

## `flet build apk`

TBD

## `flet build aab`

TBD

## `flet build ipa`

TBD

## `flet build macos`

TBD

## `flet build linux`

TBD

## `flet build windows`

TBD

## Icons

* iOS - `assets/icon_ios.png` (or any supported image format). Recommended minimum image size is 1024 px. Image should not be transparent (have alpha channel). Defaults to `assets/icon.png` with alpha-channel automatically removed.
* Android - `assets/icon_android.png` (or any supported image format). Recommended minimum image size is 192 px. Defaults to `assets/icon.png`.
* Web - `assets/icon_web.png` (or any supported image format). Recommended minimum image size is 512 px. Defaults to `assets/icon.png`. If `assets/favicon.png` file is provided it will be used unmodified (copied to `web/favicon.png`).
* Windows - `assets/icon_windows.png` (or any supported image format). ICO will be produced of 256 px size. Defaults to `assets/icon.png`. If `assets/icon_windows.ico` file is provided it will be just copied to `windows/runner/resources/app_icon.ico` unmodified.
* macOS - `assets/icon_macos.png` (or any supported image format). Recommended minimum image size is 1024 px. Defaults to `assets/icon.png`.

## Splash screens

* iOS (light) - `assets/splash_ios.png` (or any supported image format). Defaults to `assets/splash.png` and then `assets/icon.png`.
* iOS (dark) - `assets/splash_dark_ios.png` (or any supported image format). Defaults to light iOS splash, then to `assets/splash_dark.png`, then to `assets/splash.png` and then `assets/icon.png`.
* Android (light) - `assets/splash_android.png` (or any supported image format). Defaults to `assets/splash.png` and then `assets/icon.png`.
* Android (dark) - `assets/splash_dark_android.png` (or any supported image format).  Defaults to light Android splash, then to `assets/splash_dark.png`, then to `assets/splash.png` and then `assets/icon.png`.
* Web (light) - `assets/splash_web.png` (or any supported image format). Defaults to `assets/splash.png` and then `assets/icon.png`.
* Web (dark) - `assets/splash_dark_web.png` (or any supported image format). Defaults to light web splash, then `assets/splash_dark.png`, then to `assets/splash.png` and then `assets/icon.png`.

### Custom template

If you want to tweak the template you can fork template repo and then specify `gh:flet-dev/flet-build-template`.

`--template`, `--template_dir` and `--template_ref`.

### Extra args to `flutter build` command

TBD

## Known issues

* Native Python packages for iOS and Android
* Custom Flutter packages cannot be added (fork https://github.com/flet-dev/flet-build-template and add your packages to `pubspec.yaml` as a workaround).
* IPA testing

### CODE REVIEW

**Comment by jianboy** [comment]
add a command to create project, such as:

```
flet create --template flet-build-template
```

**Comment by baseplate-admin** [comment]
hi @FeodorFitsner, could you please release this ?

I been waiting so long to try this

**Comment by FeodorFitsner** [comment]
Will release it tomorrow. For now you can install pre-release: https://pypi.org/project/flet/0.18.0.dev2027/

**Comment by FeodorFitsner** [comment]
Pre-release docs: https://flet-build-docs.flet-website.pages.dev/docs/guides/python/packaging-app-for-distribution

**Comment by baseplate-admin** [comment]
Thanks a bunch

**Comment by baseplate-admin** [comment]
```powershell
PS C:\Programming\Finstagram-main> poetry run flet build apk
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4: character maps to <undefined>
OK
Generating splash screens...Exception in thread Thread-3 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\zarif\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1471: character maps to <undefined>
OK
Packaging Python app...OK
Building .apk for Android...
```

Please do note that i encountered this error while compiling apk

**Comment by baseplate-admin** [comment]
Screenshot_20231230_113846

After compiling i got this screen.

**Comment by ipcloudlive** [comment]
For me 
```
(.venv) PS C:\Users\PRO\Desktop\testpackage> flet build apk
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python312\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4: character maps to <undefined>
OK
Generating splash screens...Exception in thread Thread-3 (_readerthread):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python312\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1471: character maps to <undefined>
OK
Packaging Python app...OK
Building .apk for Android...Resolving dependencies...
  fl_chart 0.65.0 (0.66.0 available)
  flutter_lints 2.0.3 (3.0.1 available)
  flutter_native_splash 2.3.7 (2.3.8 available)
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16 (0.12.16+1 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.10.0 (1.11.0 available)
  package_info_plus 4.2.0 (5.0.1 available)
  path 1.8.3 (1.9.0 available)
  petitparser 5.4.0 (6.0.2 available)
  sensors_plus 1.4.1 (4.0.2 available)
  test_api 0.6.1 (0.7.0 available)
  toml 0.14.0 (0.15.0 available)
  uuid 4.2.2 (4.3.1 available)
  web 0.3.0 (0.4.0 available)
  web_socket_channel 2.4.0 (2.4.1 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
17 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.

Error building Flet app - see the log of failed command above.
```

**Comment by baseplate-admin** [comment]
@ipcloudlive https://stackoverflow.com/questions/68089177/flutter-building-with-plugins-requires-symlink-support

**Comment by FeodorFitsner** [comment]
@baseplate-admin what is the name of the file with your Flet app? If it's not `main.py` then use `--module-name` option to specify alternative entry-point.

**Comment by FeodorFitsner** [comment]
Fix for "charmap" error on Windows is coming!

**Comment by baseplate-admin** [comment]
> @baseplate-admin what is the name of the file with your Flet app? If it's not `main.py` then use `--module-name` option to specify alternative entry-point.

It is [`main.py`](https://github.com/tokitouq/Finstagram/blob/a69747bfdea27d6c39acaa0a360763aeb83d7371/main.py)

**Comment by FeodorFitsner** [comment]
@baseplate-admin OK. Please start a new issue and provide a full build log with `flet build apk -vv`. We'll continue there.

**Pull request merged**
