### PR TITLE
add simple django like routing

### PR DESCRIPTION
**Pull request by saurabhwadekar**
This is the first contribution of my life.
If I have done any mistake, then definitely tell me.
Thank you

### CODE REVIEW

**Comment by ndonkoHenri** [comment]
Can you explain your PR? 
What is the use case? How is it useful etc.

**Comment by saurabhwadekar** [comment]
# This makes dynamic routing easier.

Excuse me I don't know English. This has been translated by Google Translate.
Let me know if you don't understand anything

We have to write a lot of (if, else) statements for routing and passing the params to the view is very difficult.
But now all we need to do is to create a routing object in the main function and pass the page and routing list.
in routing list We'll use the path function. it returns a list
In this function we have to pass the routing url, in clear we have to (true/false) and in view we have to pass a function which will return ft.view


example:

## main.py
```python
import flet as ft
from flet_core import Routing,path
from views.index_view import IndexView
from views.next_view import NextView

def main(page: ft.Page):

    app_routes = [
        path(url="/", clear=True, view=IndexView),
        path(url="/next_view/:my_id", clear=False, view=NextView),
    ]

    Routing(page=page,app_routes=app_routes)
    page.go(page.route)

ft.app(target=main)

```

## views/index_view.py
```python
import flet as ft

def IndexView(page: ft.Page,params={}):
    print(params)
    return ft.view(
        "/",
        controls=[
            ft.Text("This Is Index View"),
            ft.ElevatedButton("Go Next View", on_click=lambda _: page.go("/next_view/10")),
        ]
    )

```

## views/next_view.py
```python
import flet as ft

def NextView(page: ft.Page,params={}):
    print(params)
    return ft.view(
        "/next_view/:my_id",
        controls=[
            ft.Text("This Is Next View"),
            ft.ElevatedButton("Go Index View", on_click=lambda _: page.go("/")),
        ]
    )

```

**Comment by FeodorFitsner** [comment]
Thanks for your efforts making the PR!

As far as I see you don't need access to any Flet internals to make your functionality work. I think instead of adding that into Flet's core you could just release it as a Python module, right?

**Comment by saurabhwadekar** [comment]
Yes it can be done. and I will definitely do it

**Comment by berecik** [comment]
@saurabhwadekar FYI with the https://github.com/Marysia-Software-Limited/flet-django package you can use directly a Django routing in your flet project, even without a Django project

**Pull request closed without merging**
