### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by AdamMusa**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Is it an empty PR?

**Comment by AdamMusa** [comment]
> Is it an empty PR?

No it's PR of ruby SDK under development

**Comment by FeodorFitsner** [comment]
Thank you! But it's nothing here: https://github.com/flet-dev/flet/pull/426/files

**Comment by AdamMusa** [comment]
> Thank you! But it's nothing here: https://github.com/flet-dev/flet/pull/426/files

Oh I see . We put it here for the moment. https://github.com/osscameroon/flet

**Comment by FeodorFitsner** [comment]
Please re-open this PR when there is something ready for review.

**Pull request closed without merging**
