### PR TITLE
Supporting `WebView` control

### PR DESCRIPTION
**Pull request by SKbarbon**
This pull request includes updates for both the Flet Flutter package and the Flet Python SDK. These updates introduce support for a WebView control on mobile platforms (iOS and Android) through the class named `MobileWebViewer`.
## peek
https://github.com/flet-dev/flet/assets/86029286/b5f4e062-0c1a-4581-be65-3d957b60af0d

## code example
```python
import flet

def main (page:flet.Page):
    page.appbar = flet.AppBar(
        title=flet.Text("WebView in flet!")
    )

    wv = flet.MobileWebViewer("http://localhost:3000/", width=400, height=650)
    page.add(wv)

flet.app(target=main)
```

## desktop suggestion
I propose we distinguish between WebView components for desktop and mobile platforms. Typically, desktop WebView contains tools tailored for desktop-class functionality, which may not be accessible on mobile due to its limited capabilities. Merging these two types of WebView may constrain the capabilities of the desktop WebView widget. To address this, I recommend intentionally separating them by naming the desktop WebView as `DesktopWebViewer` and keeping the mobile version as `MobileWebViewer`. This deliberate separation will help maintain the distinct features and capabilities of each platform.

### CODE REVIEW

**Comment by SKbarbon** [comment]
This Pull Request is related to flet `website` Pull Request:
https://github.com/flet-dev/website/pull/157

**Comment by FeodorFitsner** [comment]
Thanks for the PR!

CI is failing though - could you please take a look: https://ci.appveyor.com/project/flet-dev/flet/build/job/klmymruxukgofl60

**Comment by SKbarbon** [comment]
@FeodorFitsner oopps 🙂, any help please or suggestions from your side 👀?

**Comment by FeodorFitsner** [comment]
The problem is in https://pub.dev/packages/webview_universal package which prevents Linux client from building. What is that package for?

**Comment by SKbarbon** [comment]
@FeodorFitsner you are right, this is an unnecessary dependency. I did remove it.

**Comment by FeodorFitsner** [comment]
Thank you! Now I'd like to propose a name change for better consistency. Like in the title of this PR control is called `MobileWebView`, but in code it's called `MobileWebViewer`. I suggest we rename it to `MobileWebView`.

And I'm still not sure whether we should separate them into `Mobile` and `Desktop` WebViews. Like in control help doc you are referring to `DesktopWebView` (which does not exist yet). But what about `WebWebView` control? Is it for desktop or mobile?

So, I think we should call it just `WebView` and in the future deal with desktop and mobile differences.

**Comment by SKbarbon** [comment]
@FeodorFitsner thank you for your response!
Thats totally fine if you see that its better to just make one webview. But one of the reasons for the separating is the lack of the "universal support" for the webview. But you can absolutely decide to not do that.

Eventually, this is was for me just as an experiment to see how flet works from the inside and making like a demo to my self for future contributs.

I really can't thank you enough for your great work at flet.

**Comment by FeodorFitsner** [comment]
Good, let's rename it to `WebView` then. Also, you've probably accidentally copied some common types, please take a look: https://github.com/flet-dev/flet/pull/1865/files#diff-6e4a6372eebf7c2735b0ebd75aad81982e34497a86345f1a591d96b50f256c25R28-R70

**Comment by SKbarbon** [comment]
ok @FeodorFitsner , How does it works then now? Close this Pull Request and start a new one? Or just rename this Pull Request and push new commit for the universal webview support with fixing the issues you marked?

**Comment by FeodorFitsner** [comment]
Just rename PR and push new commit(s).

**Comment by SKbarbon** [comment]
Hello @FeodorFitsner ,
I did all the steps you did ask.
1. ✅ Rename the PR name to update the control name into `WebView`.
2. ✅ Rename the control name in the python sdk to be `WebView` instead of `MobileWebViewer`.
3. ✅ Rename the widget name in the dart (flutter) side to be `WebView` instead of `MobileWebViewer`.
4. ✅ Remove all the unnecessary types.

Hope we go more further about this PR, accepting this a current mobile control widget, then do more researches maybe in another PR for making it more universal.

**Pull request merged**
