### PR TITLE
Move to Flutter 3.22.1

### PR DESCRIPTION
**Pull request by ndonkoHenri**

### CODE REVIEW

**Comment by FeodorFitsner** [comment]
Are you going to rename `MaterialState` on Python side as well?

**Comment by ndonkoHenri** [comment]
Waiting on #3406 before resolving merge conflicts.

**Review by FeodorFitsner — APPROVED** [review]

**Comment by FeodorFitsner** [comment]
Can you resolve conflicts please?

**Comment by FeodorFitsner** [comment]
https://github.com/flet-dev/flet/pull/3406 merged - you can fix conflicts now.

**Pull request merged**
